language: go # don't install any environment

go:
  - 1.8

before_script:
  - openssl aes-256-cbc -K $encrypted_5d4e24277700_key -iv $encrypted_5d4e24277700_iv -in deploy_key.enc -out settings/keys/deploy_key -d 

install: go get -v github.com/spf13/hugo
script:
  - bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "5d4e24277700"
  - COMMIT_AUTHOR_EMAIL: "francescoaferraro@gmail.com"
