baseurl             = "https://cescoferraro.github.io/me/"
builddrafts         = true 
watch               = true 
canonifyurls        = true
relativeURLs	    = true 
contentdir          = "content/"
languageCode        = "en-US"
layoutdir           = "layouts/"
markdown	    = "org"
publishdir          = "out"
theme               = "cocoa"
author              = "@cescoferraro"
title               = "@cescoferraro"
enableEmoji 	    = true
pygmentsuseclasses  = true
disqusshortname     = "blog-cescoferraro-xyz"
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "blog/"

[[menu.main]]
name                   = "Portifolio"
weight                 = -110
identifier             = "portifolio"
title = "portifolio"
url                    = "portifolio/"

[[menu.main]]
name                   = "About"
weight                 = -90
identifier             = "about"
url                    = "about/"

[[menu.main]]
name                   = "Software"
weight                 = -100
identifier             = "software"
url                    = "software/"

[[menu.main]]
name                   = "Civil"
weight                 = -80
identifier             = "civil"
url                    = "civil/"

[params]
latestjobscount        = 3                             
latestpostscount       = 5                             
i18n_flags             = true 
author                 = "Cesco Ferraro"
cachebuster            = true                          
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
email                  = "francescoaferraro@gmail.com"
extracssfiles          = [ "/css/override.css" ]      
github                 = "//github.com/cescoferraro"
stackoverflow 	       = "//stackoverflow.com/users/3074508/cesco"
highlightjs            = true
lang                   = "en,br"
linkedin               = "//www.linkedin.com/in/francesco-ferraro-64805114/"
noshowreadtime         = false                       
selfintro              = ""                         
twitter                = "//twitter.com/cescoferraro"
highlightjslanguages   = ["python","gradle","groovy","go","java","clojure-repl"]                        
highlightjsStyle       = "atelier-estuary-dark"
avatar                 = "img/profile.png" 
DefaultContentLanguage = "en"


[Languages]
[Languages.en]
weight = 1

[Languages.br]
copyright = "Tout est à moi"
weight = 2