baseurl             = "https://cescoferraro.github.io/me/"
builddrafts         = true 
canonifyurls        = true
relativeURLs	    = true 
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
markdown	    = "org"
publishdir          = "docs"
theme               = "cocoa"
author              = "@cescoferraro"
title               = "@cescoferraro"
enableEmoji = true
pygmentsuseclasses  = true
disqusshortname     = "blog-cescoferraro-xyz" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"


[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "blog/"

[[menu.main]]
name                   = "Portifolio"
weight                 = -110
identifier             = "portifolio"
title = "portifolio"
url                    = "portifolio/"

[[menu.main]]
name                   = "About"
weight                 = -90
identifier             = "about"
url                    = "about/"

[[menu.main]]
name                   = "Software"
weight                 = -100
identifier             = "software"
url                    = "software/"

[[menu.main]]
name                   = "Civil"
weight                 = -80
identifier             = "civil"
url                    = "civil/"

[params]
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = true # whether to display small country flags for available translations
author                 = "Cesco Ferraro"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
email                  = "francescoaferraro@gmail.com"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
# faviconfile            = "img/leaf.ico"
github                 = "//github.com/cescoferraro"
highlightjs            = true
lang                   = "en,br"
linkedin               = "//linkedin.com/cescoferraro"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/cescoferraro"
mastodon               = "//example.com/@cescoferraro"
highlightjslanguages = ["go","java","clojure-repl"]                        # additional languages not included in the "common" set
highlightjsStyle     = "atelier-estuary-dark"

avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
DefaultContentLanguage = "en"
copyright = "Everything is mine"

[params.navigation]
help  = "Help"

[Languages]
[Languages.en]
weight = 1
[Languages.en.params]
linkedin = "english-link"

[Languages.br]
copyright = "Tout est à moi"
weight = 2
[Languages.br.params]
linkedin = "lien-francais"
[Languages.br.navigation]
help  = "Aide"