version: '3.2'
services:
  web:
    container_name: me
    build:
      context: ./build
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=spotify.cescoferraro.xyz
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=spotify.cescoferraro.xyz
      - LETSENCRYPT_EMAIL=francescoaferraro@gmail.com
    networks:
      global:
networks:
  global:
    external: true
