version: '3.2'
services:
  hugo:
    container_name: hugo
    build:
      context: ./out
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=www.cescoferraro.xyz
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.cescoferraro.xyz
      - LETSENCRYPT_EMAIL=francescoaferraro@gmail.com
    networks:
      global:
networks:
  global:
    external: true
