apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: blog
  name: blog-ingress
spec:
  rules:
  - host: blog.cescoferraro.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 1313
---
apiVersion: v1
kind: Service
metadata:
  namespace: blog
  name: blog
  labels:
    name: blog
spec:
  selector:
    name: blog
  ports:
  - name: web
    port: 1313
    targetPort: 1313
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: blog
  name: blog
  labels:
    name: blog
spec:
  replicas: 1
  template:
    metadata:
      namespace: blog
      labels:
        name: blog
    spec:
      containers:
        - image: cescoferraro/blog:latest
          imagePullPolicy: Always
          name: blog
          env:
          - name: KUBERNETES
            value: "true"
          - name: BRANCH
            value: "production"

